name: dpug_cli
description: Unified CLI for DPug - indentation-based Flutter/Dart syntax
version: 1.0.0

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  args: ^2.7.0
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.2
  test: ^1.26.3

executables:
  dpug: bin/dpug.dart
