name: xsoulspace_locale
description: Unified locale wrapper to make localization easier.
version: 0.2.0
homepage: https://github.com/xsoulspace/life_hooks

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  collection: ^1.19.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  from_json_to_json: ^0.2.1
  intl: ^0.20.2
  xsoulspace_foundation: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.0
