name: dpug_code_builder

environment:
  sdk: ^3.5.3

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.0.0
  collection: ^1.15.0
  meta: ^1.3.0
  code_builder: ^4.10.0
  source_span: ^1.10.0

dev_dependencies:
  analyzer: ^6.8.0
  analyzer_plugin: ^0.11.3
  build: ^2.4.1
  build_runner: ^2.4.8
  build_test: ^2.2.0
  source_gen: ^1.5.0
  test: ^1.24.0
  dart_style: ^2.3.4
  built_value_generator: ^8.9.1
