name: dpug_code_builder

environment:
  sdk: ^3.8.1

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.11.1
  code_builder: ^4.10.1
  collection: ^1.19.1
  dart_style: ^3.1.2
  meta: ^1.17.0
  source_span: ^1.10.1

dev_dependencies:
  analyzer: ^8.1.1
  analyzer_plugin: ^0.13.7
  build: ^3.0.2
  build_runner: ^2.7.0
  build_test: ^3.3.2
  built_value_generator: ^8.11.1
  lints: ^6.0.0
  source_gen: ^3.1.0
  test: ^1.26.3
  xsoulspace_lints: ^0.1.2
