name: supabase_hooks
description: Unofficial Flutter Supabase life cycle adaptation for flutter_hooks.
version: 0.0.8
homepage: https://github.com/xsoulspace/life_hooks/tree/main/packages/supabase_hooks

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  life_hooks: ^0.0.20
  supabase: ^2.6.3
  supabase_flutter: ^2.8.4
  uni_links: ^0.5.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1
  xsoulspace_lints: ^0.0.14
