name: dpug_server

environment:
  sdk: ^3.8.1

dependencies:
  dpug_core:
    path: ../dpug_core
  http: ^1.5.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  xsoulspace_lints: ^0.1.2
