name: xsoulspace_review
repository: https://github.com/xsoulspace/life_hooks/tree/main/packages/xsoulspace_review
description: Useful tools for review for stores and user feedback

version: 0.1.1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rustore_review: ^8.0.0
  in_app_review: ^2.0.10
  meta: ^1.16.0
  universal_io: ^2.2.2
  url_launcher: ^6.3.1
  wiredash: ^2.4.0
  xsoulspace_foundation: ^0.0.11
  xsoulspace_locale: ^0.0.2

dev_dependencies:
  lints: ^5.1.1
  xsoulspace_lints: ^0.0.14
