name: xsoulspace_ui_foundation
description: Shared UI utils, extensions, and helpers.
version: 0.1.0
homepage: https://github.com/xsoulspace/life_hooks/tree/main/packages/xsoulspace_ui_foundation
environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  from_json_to_json: ^0.2.0
  infinite_scroll_pagination: ^4.1.0
  store_checker: ^1.8.0
  web: ^1.1.1
  xsoulspace_foundation: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.0
